import type { Metadata } from "next";
import "./globals.css";
import { Theme } from "@radix-ui/themes";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/grs_logo.svg" sizes="any" />
      <body style={{ background: "#0D0D0D", color: "white" }}>
        <Theme>
          {children}
        </Theme>
      </body>
    </html>
  );
}
